In [1]:
!pip install numpy
import numpy as np

In [3]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))
    
def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

In [2]:
a = np.array(1.)
b = np.array([1.,2.,3.])
c = np.array([[1.,2.,3.],[4.,5.,6.]])

In [4]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [6]:
print_obj(a.ndim, "a")
print_obj(b.ndim, "b")
print_obj(c.ndim, "c")

a:
0

b:
1

c:
2



In [9]:
print_obj(a.shape, "a")
print_obj(b.shape, "b")
print_obj(c.shape, "c")
print_obj(c.shape[0], "c")

a:
()

b:
(3,)

c:
(2, 3)

c:
2



In [11]:
d = np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
e = np.array([[[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]],[[[7.,8.,9.],[10.,11.,12.]],[[10.,11.,12.],[10.,11.,12.]]]])

In [13]:
print_obj(d, "d")
print_obj(d.ndim,"d.ndim")
print_obj(d.shape, "d.shape")

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)



In [14]:
print_obj(e, "e")
print_obj(e.ndim,"e.ndim")
print_obj(e.shape, "e.shape")

e:
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]


 [[[ 7.  8.  9.]
   [10. 11. 12.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



In [17]:
a1 = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print(a1)
print(a1.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)


In [18]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
a = np.zeros((2,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
a = np.full((2,5),5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [22]:
a = np.random.random((2,3,4))
a

array([[[0.24504975, 0.52288789, 0.87283467, 0.85598525],
        [0.88050798, 0.23498962, 0.46866567, 0.70629912],
        [0.81068682, 0.08909415, 0.98480727, 0.54141373]],

       [[0.99692194, 0.49980698, 0.28244766, 0.35459952],
        [0.11441828, 0.41608623, 0.28729668, 0.47883456],
        [0.95605347, 0.58187168, 0.09490641, 0.34162185]]])

In [23]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = np.arange(10).astype(float)
a.shape

(10,)

In [30]:
a = np.arange(10).reshape(((5,2)))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
b = np.arange(24).reshape(((4,3,2)))
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [41]:
a = np.arange(10)
print_obj(a,"a")
print_obj(a[0],"a[0]")
print_obj(a[1],"a[1]")
print_obj(a[-1],"a[-1]")
print_obj(a[-3],"a[-3]")


print_obj(a[0:10], "a[0:10]")
print_obj(a[0:],"a[0:]")
print_obj(a[:],"a[:]")
print_obj(a[:10], "a[:10]")

a:
[0 1 2 3 4 5 6 7 8 9]

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[-4::
[6 7 8 9]



In [61]:
print_obj(a[-4:],"a[-4:]")
print_obj(a[:-8],"a[:-8]")


a[-4:]:
[6 7 8 9]

a[:-8]:
[0 1]



In [45]:
print_obj(a[7:],"a[7:]")
print_obj(a[:5],"a[:5]")
print_obj(a[2:5],"a[2:5]")




a[7:]:
[7 8 9]

a[:5]:
[0 1 2 3 4]

a[2:5]:
[2 3 4]



In [47]:
print_obj(a[0:10:2],"a[0:10:2]")
print_obj(a[0:10:3],"a[0:10:3]")
print_obj(a[2:6:3],"a[2:6:3]")

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]



In [50]:
print_obj(a[::-1],"a[::-1]")
print_obj(a[8:5:-1],"a[8:5:-1]")
print_obj(a[8:5],"a[8:5]")

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]



In [57]:
print_obj(a[10:0:-3],"a[10:0:-3]")

a[10:0:-3]:
[9 6 3]



In [60]:
print(a[10:0:-3],"a")

[9 6 3] a


In [63]:
a = np.arange(9).reshape((3,3))
print_obj(a[10:0:-3],"a[10:0:-3]")


a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [69]:
print_obj(a[0][0],"a")
print_obj(a[0,0],"a")
print_obj(a[1,1],"a")

a:
0

a:
0

a:
4



In [79]:
print_obj(a[-1],"a")
print_obj(a[:,1],"a")
print_obj(a[2:0:-1,2],"a")

a:
[6 7 8]

a:
[1 4 7]

a:
[8 5]



In [81]:
a = np.arange(4*3*2).reshape((4,3,2))
print_obj(a,"a")
print_obj(a[2,1,0],"a")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a:
14



In [83]:
print_obj(a[0,1],"a")

a:
[2 3]



In [97]:
print_obj(a[0:2,:,0],"a")

a:
[[ 0  2  4]
 [ 6  8 10]]



In [100]:
a =np.arange(3*2).reshape((3,2))
print_obj(a,"a")

idx = a % 2 == 0
print(idx)

print(a[idx])



a:
[[0 1]
 [2 3]
 [4 5]]

[[ True False]
 [ True False]
 [ True False]]
[0 2 4]


In [103]:
a = np.arange(24).reshape((6,4))
print_obj(a,"a")

print_obj(a[:,[0,2,3]],"a")
print_obj(a[[0,2,3],:],"a")

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]



In [105]:
idx = ((0,0,1,5),(1,2,0,3))
print_obj(a[idx],"a")

a:
[ 1  2  4 23]



In [107]:
idx1 = np.array([[0,0,1,5],[1,2,0,3]])
print_obj(a[idx1],"a")

a:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]



In [108]:
a = np.arange(6).reshape((3,2))
b = np.ones((3,2))
print_obj(a,"a")
print_obj(b,"b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]



In [109]:
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [110]:
print_obj(a.sum(),"a.sum(")
print_obj(a.sum(axis=0),"a")
print_obj(a.sum(axis=1),"a")

a.sum(:
15

a:
[6 9]

a:
[1 5 9]



In [111]:
print_obj(a.mean(),"a")
print_obj(a.max(),"a")
print_obj(a.min(),"a")

a:
2.5

a:
5

a:
0



In [115]:
a1 = np.arange(24).reshape((2,3,4))
print(a1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [118]:
a = np.arange(24).reshape((2,3,4)).sum(axis=-1).mean()
print(a)

46.0


In [119]:
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a,"a")
print_obj(b,"b")

a:
[0. 1. 2.]

b:
[1. 1. 1.]



In [120]:
print_obj(np.dot(a,b),"dot a,b")

dot a,b:
3.0



In [121]:
a = np.arange(6).reshape((3,2))
b = np.ones((2,3))
print_obj(a, "a")
print_obj(b, "b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]



In [122]:
print_obj(np.dot(a,b),"dot a,b")
print_obj(a@b,"a@b")


dot a,b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a@b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



In [123]:
a = np.arange(24).reshape((4,3,2))
b = np.ones((4,2,3))
print_obj(a, "a")
print_obj(b, "b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



In [127]:
print_obj(np.dot(a,b).shape,"a dot b")
print_obj((a@b).shape,"a@b")
print_obj(np.matmul(a,b).shape,"a matmul b")

a dot b:
(4, 3, 4, 3)

a@b:
(4, 3, 3)

a matmul b:
(4, 3, 3)



In [128]:
a = np.arange(24).reshape((4,3,2))
b = np.ones((2,3))
print_obj(a, "a")
print_obj(b, "b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]



In [130]:
print_obj(np.dot(a,b),"a dot b")

a dot b:
[[[ 1.  1.  1.]
  [ 5.  5.  5.]
  [ 9.  9.  9.]]

 [[13. 13. 13.]
  [17. 17. 17.]
  [21. 21. 21.]]

 [[25. 25. 25.]
  [29. 29. 29.]
  [33. 33. 33.]]

 [[37. 37. 37.]
  [41. 41. 41.]
  [45. 45. 45.]]]



In [131]:
print_obj((a@b),"a@b")

a@b:
[[[ 1.  1.  1.]
  [ 5.  5.  5.]
  [ 9.  9.  9.]]

 [[13. 13. 13.]
  [17. 17. 17.]
  [21. 21. 21.]]

 [[25. 25. 25.]
  [29. 29. 29.]
  [33. 33. 33.]]

 [[37. 37. 37.]
  [41. 41. 41.]
  [45. 45. 45.]]]



In [140]:
a = np.arange(24).reshape((2,3,4))
print_obj(a,"a")

b = a.reshape((6,4))
print_obj(b, "b")

c = a.reshape((6,-1))
print_obj(c,"c")

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [136]:
d = a.reshape((6,4,-1))
print_obj(d,"d")

d:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]



In [141]:
a = np.arange(3)
print_obj(a, "a")

a:
[0 1 2]



In [151]:
print_obj(a[:,None],"a")
print_obj(a[:,None].shape,"a")

a:
[[[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]]

a:
(3, 1, 4)



In [153]:
a = np.ones((3,4))
print_obj(a[:,None,None],"a")
print_obj(a[:,None,None].shape,"a")

a:
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]

a:
(3, 1, 1, 4)



In [154]:
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a,"a")
print_obj(b,"b")

a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]



In [155]:
print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.hstack([a, b]), "a,b hstack")
print_obj(np.hstack([a, b, a]), "a,b,a hstack")

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a,b,a hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]



In [156]:
print_obj(np.hstack([a, b, a,b]), "a,b,a hstack")

a,b,a hstack:
[[1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0.]]



In [157]:
print_obj(np.vstack([a, b, a]), "a,b,a hstack")

a,b,a hstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]



In [158]:
print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0")
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1")

a,b concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



In [160]:
 c = np.ones((4,3,2))
 d = np.zeros((5,4,2))

 print_obj(c,"c")
 print_obj(d,"d")

c:
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

d:
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]



In [165]:
print(np.concatenate([c,d],axis=4))

AxisError: axis 4 is out of bounds for array of dimension 3

In [166]:
print_obj(np.vstack([c,d]), "c,d hstack")

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [168]:
a = np.arange(6).reshape((3,2))
print_obj(a,"a")

print_obj(a.T,"a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



In [170]:
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")


a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]



In [171]:
b = np.transpose(a, [0, 2, 1])
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")


Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

b's shape:
(4, 2, 3)



In [172]:

c = np.transpose(a, [1, 0, 2])
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

c's shape:
(3, 4, 2)



In [173]:
d = np.transpose(a, [0, 1, 2])
print_obj(d, "d")
print_obj(d.shape, "d's shape")

d:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

d's shape:
(4, 3, 2)



In [175]:
a = np.arange(3)
b = 2.
b = np.array([2.])
print_obj(a,"a")
print_obj(b,"b")

a:
[0 1 2]

b:
[2.]



In [176]:
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]



In [177]:
# Matrix and vector
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[1 2]



In [178]:
print(b.ndim)
print(b.shape)

1
(2,)


In [179]:
b = b.reshape(1, 2)
b = b[None, :]
  
print_obj(a+b, "a+b")

a+b:
[[[1 3]
  [3 5]
  [5 7]]]



In [180]:
c = np.arange(2).reshape((2,1))
d = np.arange(2).reshape((1,2))

In [181]:
print(c)

[[0]
 [1]]


In [182]:
print(d)

[[0 1]]


In [183]:
print_obj(a+c, "a+c")

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

In [184]:
print_obj(a+d, "a+d")

a+d:
[[0 2]
 [2 4]
 [4 6]]



In [185]:
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]



In [186]:
print_obj(a+b, "a+b")

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]



In [187]:
print(a + b[None])

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]
